<?php
/**
 * @file tns_site.module
 *
 * Custom functionality for The New Schematics' website.
 */

/*  
 * Implements hook_menu().
 */
function tns_site_menu() {
  $items = array();

  $items['admin/tns'] = array(
    'title' => 'TNS',
    'description' => 'TNS Administration',
    'page callback' => 'tns_site_admin',
    'access arguments' => array('access administration menu'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => -100,
  );

  $items['admin/tns/settings'] = array(
    'title' => 'Settings',
    'description' => 'TNS site settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tns_site_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 100,
  );

  $items['admin/tns/settings/core'] = array(
    'title' => 'Core',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -100,
  );

  return $items;
}

/*
 * Page callback for admin/tns
 */
function tns_site_admin() {
  $output = array();
  
  $output[] = array(
    '#markup' => '<p>TBD</p>',
  );
  
  return $output;
}

/**
 * Form for the core settings page
 */
function tns_site_admin_settings($form, &$form_state) {
  $form[] = array(
    '#markup' => '<p>TBD</p>',
  );
  
  return $form;
}

/**
 * Implements hook_block_info().
 */
function tns_site_block_info() {
  $items = array();
  
  $items['social'] = array(
    'info' => 'TNS Social Media Links',
  );
  
  $items['kickstarter'] = array(
    'info' => 'TNS Kickstarter Button',
  );
  
  $items['breakdown'] = array(
    'info' => 'Breakdown Single Announcement',
  );
  
  $items['october2015ep'] = array(
    'info' => 'October 2015 EP',
  );

  return $items;
}

/**
 * Implements hook_block_configure().
 */
function tns_site_block_configure($delta = '') {
  $edit = array();
  
  switch ($delta) {
    case 'social': {
      $social_links = _tns_site_social_links();
      $social_links_titles = _tns_site_social_links_titles($social_links);
      
      $edit['tns_site'] = array(
        '#type' => 'fieldset',
        '#title' => t('Social Media Links'),
        '#tree' => TRUE,
      );
      
      foreach ($social_links as $key => $url) {
        $edit['tns_site'][$key] = array(
          '#type' => 'textfield',
          '#title' => !empty($social_links_titles[$key]) ? $social_links_titles[$key] : ucwords($key),
          '#default_value' => $url,
          '#description' => t('If left blank, no link will display for this social media application.'),
        );
      }
      
      break;
    }
    case 'kickstarter': {
      $url = _tns_site_kickstarter_url();
      $var = 'tns_site_kickstarter_url';
      
      $edit[$var] = array(
        '#type' => 'texfield',
        '#title' => t('Kickstarter URL'),
        '#default_value' => $url,
      );
      
      break;
    }
  }
  
  return $edit;
}

/**
 * Implements hook_block_save().
 */
function tns_site_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'social': {
      if (!empty($edit['tns_site'])) variable_set('tns_site_social_links', $edit['tns_site']);
      break;
    }
    case 'kickstarter': {
      $var = 'tns_site_kickstarter_url';
      if (isset($edit[$var])) variable_set($var, $edit[$var]);
      break;
    }
  }
}

/**
 * Implements hook_block_view().
 */
function tns_site_block_view($delta = '') {
  $block = array(
    'subject' => '',
    'content' => '',
  );
  $mod_path = drupal_get_path('module', 'tns_site');
  
  switch ($delta) {
    case 'social': {
      drupal_add_css($mod_path . '/css/tns-site.css');
      $mod_img_path = $mod_path . '/images/';
      $img_path = $mod_img_path . 'icon-';
      $bg_img_path = $mod_img_path . 'bg-icon-';
      $social_links = _tns_site_social_links();
      $social_links_titles = _tns_site_social_links_titles($social_links);
      
      $block['content'] = array(
        '#theme' => 'item_list',
        '#title' => '',
        '#type' => 'ul',
        '#attributes' => array(
          'class' => array(
            'social-media',
            'links-ul',
          ),
        ),
        '#items' => array(),
      );
      
      $items = array();
      foreach (_tns_site_social_links() as $key => $url) {
        if (empty($url)) continue;
        
        $title = !empty($social_links_titles[$key]) ? $social_links_titles[$key] : ucwords($key);
        $src = url($img_path . $key . '.png', array('absolute' => TRUE));
        $img = '<img src="' . $src . '" alt="' . $title . ' icon" title="' . $title . '">';
        
        $block['content']['#items'][] = array(
          'data' => l($img, $url, array('html' => TRUE, 'attributes' => array('target' => '_blank'))),
          'class' => array($key),
        );
      }
      
      break;
    }
    
    case 'kickstarter': {
      $url = _tns_site_kickstarter_url();
      if (empty($url)) break;
      
      $img_src = url($mod_path . '/images/kickstarter.png', array('#absolute' => TRUE));
      $link_html = '<img src="' . $img_src . '" alt="Kickstarter Logo">' . t('Back The New Schematics\' Kickstarter Project');
      
      $block['content'] = array(
        '#markup' => l($link_html, $url, array('html' => TRUE, 'attributes' => array('class' => array('kickstarter-button'), 'target' => '_blank'))),
      );
      
      break;
    }
    
    case 'breakdown': {
      $img_src = url($mod_path . '/images/breakdown-single-text.png', array('#absolute' => TRUE));
      $link_html = '<img src="' . $img_src . '" alt="New single THE BREAKDOWN out now! Debut EP due 10/2">';
      
      $block['content'] = array(
        '#markup' => l($link_html, 'http://ow.ly/QCrhF', array('html' => TRUE, 'attributes' => array('class' => array('breakdown-single-link'), 'target' => '_blank'))),
      );
      
      break;
    }
    
    case 'october2015ep': {
      $img_src = url($mod_path . '/images/20151005-bg-tv.jpg', array('#absolute' => TRUE));
      $block['content'] = array();
      
      $block['content'][] = array(
        '#markup' => '<img src="' . $img_src . '" class="debut-ep-tv" alt="A small television set displaying the logo for The New Schematics.">',
        '#prefix' => '<div class="hide-text debut-ep-img">',
        '#suffix' => 'The New Schematics</div>',
      );
      
      $block['content']['music_links'] = array(
        '#theme' => 'item_list',
        '#title' => '',
        '#type' => 'ul',
        '#attributes' => array(),
        '#items' => array(),
        '#prefix' => '<div class="debut-ep-overlay"><p>' . t('Debut EP') . '</p>',
        '#suffix' => '<p>' . t('Now Available') . '</p></div>',
      );
      
      $items = array(
        'iTunes' => 'https://itunes.apple.com/us/album/the-new-schematics-ep/id1040311337',
        'Spotify' => 'http://open.spotify.com/album/5DTNcglPrATlPTZxN96UWF',
        'Amazon' => 'http://amzn.com/B015GR5R90',
        'Google' => 'https://play.google.com/store/music/album/The_New_Schematics_The_New_Schematics?id=Bmtarvedake456ukqru4bbovcue',
      );
      
      foreach ($items as $item => $url) {
        $img = '<img src="' . url($mod_path . '/images/icon-debut-ep-' . strtolower($item) . '.png', array('#absolute' => TRUE)) . '" alt="' . $item . '">';
        
        $options = array();
        $options['attributes'] = array(
          'target' => '_blank',
          'class' => array(
            'debut-ep-music-link',
            strtolower($item),
            'hide-text',
          ),
        );
        
        $options['html'] = TRUE;
        
        $block['content']['music_links']['#items'][] = l($img . $item, $url, $options);
      }
      
      break;
    }
  }
  
  return $block;
}

/**
 * Implements hook_form_alter().
 */
function tns_site_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['#node']) && !empty($form['#node']->webform) && strpos($form_id, 'webform_client_form') !== FALSE) {
    $placeholders = array();
    
    foreach ($form['#node']->webform['components'] as $index => &$field) {
      if (!empty($field['extra']['title_display']) && $field['extra']['title_display'] == 'inline' && empty($field['extra']['placeholder'])) {
        $field['extra']['placeholder'] = $field['name'];
      }
      
      if (!empty($field['extra']['placeholder'])) {
        $placeholders[$field['name']] = $field['extra']['placeholder'];
      }
    }
    
    foreach ($form['submitted'] as &$field) {
      if (!is_array($field) || empty($field['#type'])) continue;
      if (!empty($placeholders[$field['#title']])) {
        $field['#attributes']['placeholder'] = $placeholders[$field['#title']];
        $field['#title_display'] = 'invisible';
      }
    }
  }
}

/**
 * Helper function for getting the social links variable data
 */
function _tns_site_social_links() {
  $defaults = array(
    'facebook' => '//www.facebook.com/TheNewSchematics',
    'twitter' => '//www.twitter.com/NewSchematics',
    'youtube' => '//www.youtube.com/channel/UC_N0TieqL3SxQoAdD8yMHYg',
    'instagram' => '//www.instagram.com/TheNewSchematics',
    'spotify' => '//open.spotify.com/album/6BZfV8voWY1y0eD2tBPzTH',
    'itunes' => '//ow.ly/Mwbyz',
  );
  
  return variable_get('tns_site_social_links', $defaults);
}

/**
 * Helper function for formatting the social links variable titles
 */
function _tns_site_social_links_titles($social_links = array()) {
  if (empty($social_links)) $social_links = _tns_site_social_links();
  
  $output = array();
  foreach ($social_links as $key => $url) {
    if (in_array($key, array('youtube', 'itunes'))) {
      $title = $key == 'youtube' ? 'YouTube' : 'iTunes';
    }
    else {
      $title = ucwords($key);
    }
    
    $output[$key] = $title;
  }
  
  return $output;
}

/**
 * Helper function for getting the social links variable data
 */
function _tns_site_kickstarter_url() {
  $var = 'tns_site_kickstarter_url';
  $default = 'https://www.kickstarter.com/projects/thenewschematics/the-new-schematics-debut-ep';
  return variable_get($var, $default);
}